// @title Go-Task-Scheduler API
// @version 1.0
// @description This is the API documentation for the Go-Task-Scheduler project.
// @host localhost:3000
// @BasePath /

package main

import (
	_ "pulse/admin/docs" // docs is generated by Swag CLI
)


import (
	"fmt"
	"os"
	"pulse/admin/internal/handler"
	"pulse/admin/internal/service"
	"pulse/common/pkg/config"
	"pulse/common/pkg/dbclient"
	"pulse/common/pkg/logger"
	"pulse/common/pkg/notify"
	"pulse/common/pkg/server"
	"time"
)

const ServerName = "admin"

func main() {
	// 1. 创建并初始化一个新的 API 服务实例
	srv, err := server.NewApiServer(ServerName)
	if err != nil {
		logger.GetLogger().Error(fmt.Sprintf("new api server error:%s", err.Error()))
		os.Exit(1)
	}

	// 2. 注册 API 路由
	srv.RegisterRouters(handler.RegisterRouters)

	// 3. 启动节点监视器服务
	service.DefaultNodeWatcher = service.NewNodeWatcherService()
	err = service.DefaultNodeWatcher.Watch()
	if err != nil {
		logger.GetLogger().Error(fmt.Sprintf("resolver  error:%#v", err))
	}

	// 4. 初始化数据库表结构
	err = service.RegisterTables(dbclient.GetMysqlDB())
	if err != nil {
		logger.GetLogger().Error(fmt.Sprintf("init db table error:%#v", err))
	}

	// 5. 在后台启动通知服务
	go notify.Serve()

	// 6. 启动后台日志清理任务
	var closeChan chan struct{} // 用于在服务关闭时通知日志清理器停止
	// 从配置中读取日志清理周期
	period := config.GetConfigModels().System.LogCleanPeriod
	if period > 0 { // 如果配置了清理周期
		// 启动一个定时任务，定期清理过期的日志文件
		closeChan = service.RunLogCleaner(time.Duration(period)*time.Minute, config.GetConfigModels().System.LogCleanExpiration)
	}

	// 7. 启动 API 服务器并开始监听端口
	// ListenAndServe 是一个阻塞操作，它会启动 HTTP 服务器并处理传入的 API 请求
	err = srv.ListenAndServe()
	if err != nil {
		// 如果服务器启动失败或异常退出
		logger.GetLogger().Error(fmt.Sprintf("startup api server error:%v", err.Error()))
		close(closeChan) // 通知日志清理器停止
		os.Exit(1)
	}

	// 正常退出
	os.Exit(0)
}
