version: '3.8'

services:
#  etcd:
#    image: 'bitnami/etcd:latest'
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
#    ports:
#      - "2379:2379"
#    networks:
#      - pulse-net

#  mariadb:
#    image: 'mariadb:10.6'
#    environment:
#      - MARIADB_ROOT_PASSWORD=mysecretpassword
#      - MARIADB_USER=pulse_user
#      - MARIADB_PASSWORD=123456
#      - MARIADB_DATABASE=pulse
#    ports:
#      - "3306:3306"
#    volumes:
#      - mariadb_data:/var/lib/mysql
#    networks:
#      - pulse-net

  node1:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        - HTTP_PROXY=http://host.docker.internal:7890
        - HTTPS_PROXY=http://host.docker.internal:7890
        - NO_PROXY=localhost,127.0.0.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./_mock_node/docker_conf/node1.json:/app/node/conf/testing/node1.json
    command: ["--environment=testing", "--configfilename=node1"]
    networks:
      - pulse-net
#    depends_on:
#      - etcd
#      - mariadb

  node2:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        - HTTP_PROXY=http://host.docker.internal:7890
        - HTTPS_PROXY=http://host.docker.internal:7890
        - NO_PROXY=localhost,127.0.0.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./_mock_node/docker_conf/node2.json:/app/node/conf/testing/node2.json
    command: ["--environment=testing", "--configfilename=node2"]
    networks:
      - pulse-net
#    depends_on:
#      - etcd
#      - mariadb
      
  node3:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        - HTTP_PROXY=http://host.docker.internal:7890
        - HTTPS_PROXY=http://host.docker.internal:7890
        - NO_PROXY=localhost,127.0.0.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./_mock_node/docker_conf/node3.json:/app/node/conf/testing/node3.json
    command: ["--environment=testing", "--configfilename=node3"]
    networks:
      - pulse-net
#    depends_on:
#      - etcd
#      - mariadb

  node4:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        - HTTP_PROXY=http://host.docker.internal:7890
        - HTTPS_PROXY=http://host.docker.internal:7890
        - NO_PROXY=localhost,127.0.0.1
      extra_hosts:
        - "host.docker.internal:host-gateway"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./_mock_node/docker_conf/node4.json:/app/node/conf/testing/node4.json
    command: ["--environment=testing", "--configfilename=node4"]
    networks:
      - pulse-net
#    depends_on:
#      - etcd
#      - mariadb

networks:
  pulse-net:
    driver: bridge

#volumes:
#  mariadb_data: